---
title: "Missing Migrants"
author: 
  - TIKICI, Enes[1]
bibliography: ../bibliography/biblio.bib
csl: ../csl/apa.csl
header-includes:
  - \usepackage{polyglossia}
  - \setmainlanguage{english}
  - \usepackage{booktabs}
  - \usepackage{caption} 
  - \captionsetup[table]{skip=10pt}
output:
  bookdown::pdf_document2:
    fig_caption: yes
    fig_height: 3
    fig_width: 4
    keep_tex: no
    latex_engine: xelatex
    number_sections: yes
    toc: no
geometry: margin=1in
link-citations: yes
urlcolor: blue
fontsize: 12pt
biblio-style: apalike
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, echo = TRUE, message = FALSE, warning = FALSE)
```

<!-- ======================================================================= -->
<!-- ============================== FOOTNOTES ============================== -->
<!-- ======================================================================= -->
[^1]: 20080503, [Github Repo](https://github.com/YOUR_USER_NAME_HERE/YOUR_REPO_NAME_HERE)

# Important Information About Midterm

\colorbox{BurntOrange}{WRITE YOUR GITHUB REPO LINK ON LINE 35 IN THIS FILE!}

**Project Proposal submisson will be done by uploading a zip file to the ekampus system along with the Github repo link. If you do not upload a zip file to the system and do not provide a Github repo link, you will be deemed not to have entered the midterm and final exams.**

**You must upload your project folder (`YourStudentID.zip` file) to *ekampus.ankara.edu.tr* until 16 April 2023, 23:59.**

\colorbox{WildStrawberry}{Read the README.md file in the project folder for more information.}

# Introduction
The purpose of my work is to examine the dataset on missing-immigrants. First of all, I accessed this dataset from the website of The International Organization for Migration (IOM). This dataset includes immigrants who lost their lives or disappeared in the first quarter of 2023, taking into account various variables. Some of these variables are: the region where the incident occurred, the year and month it occurred, the gender of those who lost their lives, the region in which they were trying to migrate, etc. This dataset I found includes 220 observations and 23 variables, but some of these observations and variables will not be included in the analysis in this study. The basic question that I will try to answer in the literature review section is “Where and in which region the most deaths occur during migration and how these immigrants lose their lives?” will be. This question is directly related to the articles I found and my dataset, and I will address this question in detail in the literature review section.

## Literature Review

Due to various reasons such as economic inadequacy, violation of human rights, destruction of the rule of law, severe restriction of individual freedoms, chaos in the country, racism, individuals may decide to immigrate from their country of origin, either on their own or with their families, and may be compelled to do so. . The loss of their lives on the migration route of these individuals who decide to immigrate is called "missing immigrants" in the international arena. Since 2014, when the missing migrants were documented, more than 50 thousand people lost their lives during this migration. 29,126 of these 50 thousand people planned to migrate to Europe. Of these 29,126 people, 25,104 died by drowning in the Mediterranean.(@ahmad2021anatomy,). Autopsies are usually not performed for these immigrants who lost their lives because most of them died by drowning. Identification of the deceased migrant is usually done by their close relatives - if there is a specific mark on their body. Otherwise, it is identified and identified by fingerprint(@robins2022affective,). The data currently available indicate that deaths directly related to border control at land borders are higher than at sea. However, for the vast majority, the cause of death is only indirectly related to border control. While most boat migrants die from suffocation, hypothermia and thirst, most stowaways seem to die of suffocation and thirst(@last2014tracking,). This issue of missing immigrants is an issue that the international public does not pay enough attention to. Most deaths occur in the Mediterranean, as immigrants usually plan to migrate to Europe via the Mediterranean. There are certain families that want to attract the attention of the international public on this issue, one of them is a family that mourns and struggles for every common grave in the Mediterranean, and often takes political steps to find the truth about their loved ones and honor their remains (@kovras2016death,).


**References section is created automatically by Rmarkdown. There is no need to change the references section in the draft file.**

**_You shouldn't delete the last 3 lines. Those lines are required for References section._**

\newpage
# References {#references}
<div id="refs"></div>

